variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.3.9-jdk-8

stages:
  - prepare
  - build
  - test
  - report

cache:
  paths:
    - .m2/repository

setup:
  stage: prepare
  script:
    - echo "Cleaning output directories"
    - 'mvn $MAVEN_CLI_OPTS clean'   

build-tests:
  stage: build
  script:
    - echo "Compiling changes from $CI_JOB_NAME:$CI_COMMIT_SHORT_SHA"
    - 'mvn $MAVEN_CLI_OPTS -DskipTests test-compile'   

test-api:
  stage: test
  script:
    - echo "Starting API tests execution"
    - 'mvn $MAVEN_CLI_OPTS verify' 
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
      - target/site/serenity/
    expire_in: 1 week
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml  

serenity-report:
  stage: report
  only:
    - master
  script:
    - mkdir public
    - mv target/site/serenity/* public
  artifacts:
    when: always
    paths:
      - public
    expire_in: 1 week        
